import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  const AppLocalizations(this.locale);

  bool get isArabic => locale.languageCode == 'ar';

  static AppLocalizations of(BuildContext context) {
    final locale = Localizations.localeOf(context);
    return AppLocalizations(locale);
  }

  static TextDirection textDirectionOf(BuildContext context) {
    final locale = Localizations.localeOf(context);
    return locale.languageCode == 'ar' ? TextDirection.rtl : TextDirection.ltr;
  }

  String t(String key) {
    final map = isArabic ? _ar : _en;
    return map[key] ?? key;
  }
}

const Map<String, String> _en = {
  'settings': 'Settings',
  'status_message': 'Status Message',
  'dark_mode': 'Dark Mode',
  'language': 'Language',
  'arabic': 'Arabic',
  'english': 'English',
  'private_lock': 'Private Lock',
  'allow_calls': 'Allow Calls',
  'all': 'All',
  'auto_join_stream': 'Auto join stream',
  'hide_activity_status': 'Hide activity status',
  'email': 'Email',
  'birthdate': 'Birthdate',
  'country': 'Country',
  'egypt': 'Egypt',
  'gender': 'Gender',
  'male': 'Male',
  'change_password': 'Change Password',
  'blocked_users': 'Blocked users',
  'sessions_log': 'Sessions Log',
  'delete_my_account': 'Delete my account',
  'more': 'More',
  'privacy_policy': 'Privacy Policy',
  'terms': 'Terms And Conditions',
  'logout': 'Logout',
  'edit_cover': 'Edit cover clicked',
  'edit_avatar': 'Edit avatar clicked',
    'home': 'Home',
'search': 'Search',
'no_rooms_now': 'No rooms available now',
'room_banned': 'You are banned from this room',
'room_not_found': 'Room not found',
'room_password_required': 'This room requires a password',
'wrong_room_password': 'The room password is incorrect',
'room_members_only': 'This room is for members only',
'room_join_failed': 'Unable to join the room',
'room_not_joined': 'You must join the room first',
'error_occurred': 'An error occurred',
'room_password': 'Room Password',
'enter_password': 'Enter the password',
'cancel': 'Cancel',
'enter': 'Enter',
'members_only_title': 'Members Only',
'members_only_message':
    'You cannot enter this room now because it is restricted to members only.',
'ok': 'OK',
'public_rooms': 'Public',
'voice_rooms': 'Voice',
'active_rooms': 'Active',
'favorite_rooms': 'Favorites',
  'rooms': 'Rooms',
  'chats': 'Chats',
  'friends': 'Friends',
  'name': 'Name',
'enter_username_only': 'Enter username only',
'enter_username': 'Enter the username',
'ban_request_sent': 'Ban request sent',
'add_request_sent': 'Add request sent',
'remove': 'Remove',
'save': 'Save',
'room_password_removed': 'Room password removed',
'enter_valid_password': 'Enter a valid password',
'password_change_sent': 'Password change request sent',
'pinned_message': 'Pinned Message',
'write_pinned_message': 'Write pinned message',
'pinned_message_removed': 'Pinned message removed',
'pinned_message_sent': 'Pinned message sent',
'room_locked_members_only': 'Room locked for members only',
'room_opened_for_everyone': 'Room opened for everyone',
'favorite_update_sent': 'Favorite update sent',
'room_boost_sent': 'Room boost sent',
'active_users': 'Active Users',
'no_active_users': 'No active users now',
'no_users_here': 'No users here',
'remove_role_request_sent': 'Remove role request sent',
'add_banned_user': 'Add banned user',
'not_connected_yet': 'is not connected yet',
'online': 'Online',
'favorite': 'Favorite',
'boost': 'Boost',
'members_only': 'Members Only',
'password': 'Password',
'password_is_active': 'Password is active',
'no_password': 'No password',
'no_pinned_message': 'No pinned message',
'remove_favorite': 'Remove Favorite',
'add_favorite': 'Add Favorite',
'current_favorites': 'Current favorites',
'boost_room': 'Boost Room',
'current_boost_score': 'Current boost score',
'owners': 'Owners',
'admins': 'Admins',
'members': 'Members',
'outcasts': 'Outcasts',
'room_logs': 'Room Logs',
'reset_banned_ip': 'Reset banned IP',
'reset_banned_ip_description':
    'Remove all banned IP addresses now. This requires a backend handler.',
'reset_room': 'Reset Room',
'reset_room_description':
    'Reset the room and remove all roles except the creator. This requires a backend handler.',
'user': 'User',
'users': 'Users',
'no_users_online': 'No users online',
'close': 'Close',
'gift': 'Gift',
'message': 'Message',

'owner': 'Owner',
'admin': 'Admin',
'member': 'Member',
'normal_user': 'User',
'banned': 'Banned',

'copy': 'Copy',
'send_gift': 'Send Gift',
'kick': 'Kick',
'ban': 'Ban',
'set_member': 'Set Member',
'set_admin': 'Set Admin',
'set_owner': 'Set Owner',
'remove_role': 'Remove Role',
'banned_users': 'Banned Users',
'no_banned_users': 'No banned users',
'banned_ips': 'Banned IPs',
'no_banned_ips': 'No banned IPs',
'no_logs': 'No logs',

  'store': 'Store',
  'search_chats_or_messages': 'Search chats or messages',
'clear_search': 'Clear search',
'notifications': 'Notifications',
'menu': 'Menu',
'add_friend': 'Add Friend',
'search_username': 'Search username',
'search_by_username': 'Search by username',
'no_users_found': 'No users found',
'add': 'Add',
'friend_request_sent_to': 'Friend request sent to',
  
};

const Map<String, String> _ar = {
  'settings': 'الإعدادات',
  'status_message': 'رسالة الحالة',
  'dark_mode': 'الوضع الداكن',
  'language': 'اللغة',
  'arabic': 'العربية',
  'english': 'الإنجليزية',
  'private_lock': 'قفل الخصوصية',
  'allow_calls': 'السماح بالمكالمات',
  'all': 'الكل',
  'auto_join_stream': 'دخول البث تلقائيًا',
  'hide_activity_status': 'إخفاء حالة النشاط',
  'email': 'البريد الإلكتروني',
  'birthdate': 'تاريخ الميلاد',
  'country': 'الدولة',
  'egypt': 'مصر',
  'gender': 'النوع',
  'male': 'ذكر',
  'change_password': 'تغيير كلمة المرور',
  'blocked_users': 'المستخدمون المحظورون',
  'sessions_log': 'سجل الجلسات',
  'delete_my_account': 'حذف حسابي',
  'more': 'المزيد',
  'privacy_policy': 'سياسة الخصوصية',
  'terms': 'الشروط والأحكام',
  'logout': 'تسجيل الخروج',
  'edit_cover': 'تعديل الغلاف',
  'edit_avatar': 'تعديل الصورة',
    'home': 'الرئيسية',
  'rooms': 'الغرف',
  'chats': 'المحادثات',
  'friends': 'الأصدقاء',
  'store': 'المتجر',
  'search_chats_or_messages': 'البحث في المحادثات أو الرسائل',
'clear_search': 'مسح البحث',
'add_friend': 'إضافة صديق',
'notifications': 'الإشعارات',
'menu': 'القائمة',
'search_username': 'البحث باسم المستخدم',
'search_by_username': 'ابحث باسم المستخدم',
'no_users_found': 'لم يتم العثور على مستخدمين',
'add': 'إضافة',
'friend_request_sent_to': 'تم إرسال طلب صداقة إلى',
'search': 'بحث',
'no_rooms_now': 'لا توجد غرف الآن',
'room_banned': 'أنت محظور من هذه الغرفة',
'room_not_found': 'الغرفة غير موجودة',
'room_password_required': 'هذه الغرفة تحتاج كلمة مرور',
'wrong_room_password': 'كلمة مرور الغرفة غير صحيحة',
'room_members_only': 'هذه الغرفة للأعضاء فقط',
'room_join_failed': 'تعذر دخول الغرفة',
'name': 'الاسم',
'enter_username_only': 'اكتب اسم المستخدم فقط',
'enter_username': 'اكتب اسم المستخدم',
'ban_request_sent': 'تم إرسال طلب الحظر',
'add_request_sent': 'تم إرسال طلب الإضافة',
'room_password': 'كلمة مرور الغرفة',
'enter_password': 'اكتب كلمة المرور',
'remove': 'إزالة',
'cancel': 'إلغاء',
'save': 'حفظ',
'room_password_removed': 'تم حذف كلمة مرور الغرفة',
'enter_valid_password': 'اكتب كلمة مرور صحيحة',
'password_change_sent': 'تم إرسال طلب تغيير كلمة المرور',
'pinned_message': 'الرسالة المثبتة',
'write_pinned_message': 'اكتب الرسالة المثبتة',
'pinned_message_removed': 'تم إلغاء الرسالة المثبتة',
'pinned_message_sent': 'تم إرسال الرسالة المثبتة',
'room_locked_members_only': 'تم قفل الغرفة للأعضاء فقط',
'room_opened_for_everyone': 'تم فتح الغرفة للجميع',
'favorite_update_sent': 'تم إرسال تحديث المفضلة',
'room_boost_sent': 'تم إرسال تعزيز الغرفة',
'active_users': 'المستخدمون النشطون',
'users': 'المستخدمون',
'no_users_online': 'لا يوجد مستخدمون متصلون',
'close': 'إغلاق',
'user': 'مستخدم',
'gift': 'هدية',
'message': 'مراسلة',

'owner': 'مالك',
'admin': 'مشرف',
'member': 'عضو',
'normal_user': 'مستخدم',
'banned': 'محظور',

'copy': 'نسخ',
'send_gift': 'إرسال هدية',
'kick': 'طرد',
'ban': 'حظر',
'set_member': 'تعيين كعضو',
'set_admin': 'تعيين كمشرف',
'set_owner': 'تعيين كمالك',
'remove_role': 'إزالة الرتبة',
'no_active_users': 'لا يوجد مستخدمون نشطون الآن',
'no_users_here': 'لا يوجد مستخدمون هنا',
'remove_role_request_sent': 'تم إرسال طلب حذف الرتبة',
'add_banned_user': 'إضافة مستخدم محظور',
'not_connected_yet': 'غير مربوط حاليًا',
'online': 'المتصلون',
'favorite': 'المفضلة',
'boost': 'التعزيز',
'members_only': 'للأعضاء فقط',
'password': 'كلمة المرور',
'password_is_active': 'كلمة المرور مفعلة',
'no_password': 'لا توجد كلمة مرور',
'no_pinned_message': 'لا توجد رسالة مثبتة',
'remove_favorite': 'إزالة من المفضلة',
'add_favorite': 'إضافة إلى المفضلة',
'current_favorites': 'عدد المفضلة الحالي',
'boost_room': 'تعزيز الغرفة',
'current_boost_score': 'نقاط التعزيز الحالية',
'owners': 'المالكون',
'admins': 'المشرفون',
'members': 'الأعضاء',
'outcasts': 'المحظورون',
'room_logs': 'سجل الغرفة',
'reset_banned_ip': 'إعادة ضبط عناوين IP المحظورة',
'reset_banned_ip_description':
    'إزالة جميع عناوين IP المحظورة الآن. يتطلب ذلك معالجًا في الخادم.',
'reset_room': 'إعادة ضبط الغرفة',
'reset_room_description':
    'إعادة ضبط الغرفة وإزالة جميع الرتب ما عدا المنشئ. يتطلب ذلك معالجًا في الخادم.',
'banned_users': 'المستخدمون المحظورون',
'no_banned_users': 'لا يوجد مستخدمون محظورون',
'banned_ips': 'عناوين IP المحظورة',
'no_banned_ips': 'لا توجد عناوين IP محظورة',
'no_logs': 'لا توجد سجلات',
'room_not_joined': 'يجب دخول الغرفة أولًا',
'error_occurred': 'حدث خطأ',
'enter': 'دخول',
'members_only_title': 'الغرفة للأعضاء فقط',
'members_only_message':
    'لا يمكنك دخول هذه الغرفة الآن لأنها مخصصة للأعضاء فقط.',
'ok': 'حسنًا',
'public_rooms': 'العامة',
'voice_rooms': 'الصوتية',
'active_rooms': 'النشطة',
'favorite_rooms': 'المفضلة',
};
